version: '3.8'

services:
  web:
    build: .
    container_name: stockease_web
    volumes:
      - .:/app
    ports:
      - "10000:10000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy  
    networks:
      - stockease_network

  db:
    image: postgres:15
    container_name: stockease_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stockease_network

  redis:
    image: redis:alpine
    container_name: stockease_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stockease_network

volumes:
  postgres_data:

networks:
  stockease_network: