app = "stockease"  # Replace with your app name

[build]
  # No need to specify a Dockerfile if using mise
  # You can specify the build command if needed
  # command = "mise build"

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  PORT = "10000"