app = "stockease"  # Replace with your app name

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  PORT = "10000"